                                //  Project made by Gabriel Barbosa //

1. Thx for opening my project.

2. The project deals with the increase of cards from the emergence of betting houses in Brazil, for this, data from
championships before and after the emergence of these betting stands was used, with the objective of observing if there
is any change in the generated graphics.

3. The project aims to verify if there is an increase in the number of cards in the Brazilian Football Championship
after the popularization of sports betting houses in the country.

                                        // Instructions //

1. Run main.py in any IDE that supports python and you will have access to spreadsheets of card numbers via Output and
you will have access to the graphs generated by MatPlotLib.
